### ISSUE TITLE
Add distance-perhaps other parameters

### ISSUE THREAD

**Issue by LynnAshley99** [dhcgn/jxlgui#6]
Thanks!- A gui for jxl is sorely lacking!  I even considered trying to pick up the pieces of MegaPixel Qt-which was the best so far. Perhaps look at it and as I said add distance other parameters-regardless thanks!

**Comment by dhcgn** [comment]
Thank you, for your input. 

All Parameters will be add in near future with https://github.com/dhcgn/jxlgui/issues/2.

An [GUI for configuration](https://github.com/dhcgn/jxlgui/issues/7) is documented, but not first prio, because it adds only comfort to the text based configuration.

**Comment by dhcgn** [comment]
You can now use `distance` or `quality` to convert images.
![image](https://user-images.githubusercontent.com/6566207/178155902-38bc7708-fc44-45fe-b3bc-4c0a888cbee9.png)

### Use Quality
![image](https://user-images.githubusercontent.com/6566207/178155911-0006b5e9-ada8-4abf-b94b-d2640520b3eb.png)

### Use Distance
![image](https://user-images.githubusercontent.com/6566207/178155923-c949dd82-4018-4e66-b5ca-5a133c5afadf.png)

### Error when using both
![image](https://user-images.githubusercontent.com/6566207/178155957-1785279e-250d-4cec-8ce7-8040205009ee.png)

Release will be uploaded today.

**Comment by dhcgn** [comment]
https://github.com/dhcgn/jxlgui/releases/tag/v1.0.4
